server:
  port: 8761  # Eureka????

spring:
  application:
    name: discovery-service  # ????

eureka:
  client:
    register-with-eureka: false  # ??????
    fetch-registry: false        # ??Eureka??????
  server:
    enable-self-preservation: false  # ???????????????
    eviction-interval-timer-in-ms: 30000  # ??????????? (30?)
  instance:
    prefer-ip-address: true  # ??IP????????

# ?????????
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # ?????
  endpoint:
    health:
      show-details: always  # ????????
